  name: Build Exercicio 3
  on:
    push:
      branches:
        - develop
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/setup-node@v2
        with:
          node-version: 20 
      - name: Install dependencies
        run: npm install 
      - name: Debug
        run: ls -l directory_contents_before.txt
      - name: Build TypeScript
        run: npx tsc ./src
      - name: Debug
        run: ls -l directory_contents_after.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # name: dist  
          # path: dist
          name: debug
          path: |
            directory_contents_before.txt
            directory_contents_after.txt   
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 
