  name: Build develop
  on:
    push:
      branches:
        - develop
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/setup-node@v2
        with:
          node-version: 20 
      - name: Install dependencies
        run: npm install 
      - name: Build TypeScript
        run: | 
          cp -r ./* dist/ 
          npx tsc
        working-directory: ${{ github.workspace }} 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/   
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download dos artefatos
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

   

